---
all:
  children:
    windows:
      hosts:
        tmpdom:
          ansible_host: 172.16.5.221
      vars:
        ansible_connection: winrm
        ansible_port: 5985
        ansible_winrm_transport: basic
        ansible_user: solaire
        ansible_password: 1qaz2wsx!QAZ@WSX
